# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo $(pwd)
  displayName: 'Run a multi-line script'

schedules:
- cron: "12 14 * * *"
  displayName: "scheduled"
  branches:
    include: 
      - main
  always: true