# Bash
# Run a Bash script on macOS, Linux, or Windows
schedules:
- cron: "12 14 * * *"
  displayName: "scheduled"
  branches:
    include: 
      - main
  always: true
steps:
- task: Bash@1
  inputs:
    targetType: 'filePath' # Optional. Options: filePath, inline
    filePath: 'script.sh' # Required when targetType == FilePath
 
